apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx123
  name: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      run: nginx123
  template:
    metadata:
      labels:
        run: nginx123
    spec:
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: pvc-nfs-pv3
      containers:
      - name: nginx-hit
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
