apiVersion: v1
kind: Pod
metadata:
  name: quota-mem-cpu-demo3
spec:
  containers:
  - name: quota-mem-cpu-demo-ctr3
    image: nginx
    resources:
      limits:
        memory: "200Mi"
        cpu: "200m"
      requests:
        memory: "100Mi"
        cpu: "100m"
